name: common_toolkit
description: "通用工具包"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer_animation: 2.2.1
  extended_image: 8.2.1
  loading_animation_widget: 1.2.1
  lottie: 3.1.2
  flutter_bloc: 8.1.6
  bloc: 8.1.4
  path_provider: 2.1.4
  android_id: 0.4.0
  device_info_plus: 10.1.0
  package_info_plus: 8.0.0
  flutter_secure_storage: 9.2.2
  uuid: 4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/lottie/