name: pull_to_refresh_flutter3
description: a widget provided to the flutter scroll component drop-down refresh and pull up load.
version: 2.0.2
homepage: https://github.com/xxzj990-game/flutter_pulltorefresh

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
